# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [11]:
#Import your libraries
import pandas as pd
import numpy as np
import datetime


# Challenge 1 - Import and Describe the Dataset

#### In this challenge we will use the `austin_weather.csv` file. 

#### First import it into a data frame called `austin`.

In [4]:
# Your code here
df = pd.read_csv('../austin_weather.csv')

#### Next, describe the dataset you have loaded: 
- Look at the variables and their types
- Examine the descriptive statistics of the numeric variables 
- Look at the first five rows of all variables to evaluate the categorical variables as well

In [8]:
df.shape

(1319, 21)

In [18]:
date = pd.to_datetime(df['Date'])
df['Date'] = date

In [19]:
# Your code here
df.dtypes

Date                          datetime64[ns]
TempHighF                              int64
TempAvgF                               int64
TempLowF                               int64
DewPointHighF                         object
DewPointAvgF                          object
DewPointLowF                          object
HumidityHighPercent                   object
HumidityAvgPercent                    object
HumidityLowPercent                    object
SeaLevelPressureHighInches            object
SeaLevelPressureAvgInches             object
SeaLevelPressureLowInches             object
VisibilityHighMiles                   object
VisibilityAvgMiles                    object
VisibilityLowMiles                    object
WindHighMPH                           object
WindAvgMPH                            object
WindGustMPH                           object
PrecipitationSumInches                object
Events                                object
dtype: object

In [7]:
# Your code here
df.describe()

         TempHighF     TempAvgF     TempLowF
count  1319.000000  1319.000000  1319.000000
mean     80.862775    70.642911    59.902957
std      14.766523    14.045904    14.190648
min      32.000000    29.000000    19.000000
25%      72.000000    62.000000    49.000000
50%      83.000000    73.000000    63.000000
75%      92.000000    83.000000    73.000000
max     107.000000    93.000000    81.000000

In [10]:
# Your code here
display(df.head())
display(df['Events'].value_counts())

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,

                             903
Rain                         192
Rain , Thunderstorm          137
Fog , Rain , Thunderstorm     33
Fog                           21
Thunderstorm                  17
Fog , Rain                    14
Fog , Thunderstorm             1
Rain , Snow                    1
Name: Events, dtype: int64

#### Given the information you have learned from examining the dataset, write down three insights about the data in a markdown cell below

your insights here

1)

#### Let's examine the DewPointAvgF variable by using the `unique()` function to list all unique values in this dataframe.

Describe what you find in a markdown cell below the code. What did you notice? What do you think made Pandas to treat this column as *object* instead of *int64*?

In [20]:
# Your code here
df['DewPointAvgF'].unique()

array(['49', '36', '27', '28', '40', '39', '41', '26', '42', '22', '48',
       '32', '8', '11', '45', '55', '61', '37', '47', '25', '23', '20',
       '33', '30', '29', '17', '14', '13', '54', '59', '15', '24', '34',
       '35', '57', '50', '53', '60', '46', '56', '51', '31', '38', '62',
       '43', '63', '64', '67', '66', '58', '70', '68', '65', '69', '71',
       '72', '-', '73', '74', '21', '44', '52', '12', '75', '76', '18'],
      dtype=object)

In [ ]:
# Your observation here

The following is a list of columns misrepresented as `object`. Use this list to convert the columns to numeric using the `pandas.to_numeric` function in the next cell. If you encounter errors in converting strings to numeric values, you need to catch those errors and force the conversion by supplying `errors='coerce'` as an argument for `pandas.to_numeric`. Coercing will replace non-convertable elements with `NaN` which represents an undefined numeric value. This makes it possible for us to conveniently handle missing values in subsequent data processing.

*Hint: you may use a loop to change one column at a time but it is more efficient to use `apply`.*

In [ ]:
wrong_type_columns = ['DewPointHighF', 'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent', 
                      'HumidityAvgPercent', 'HumidityLowPercent', 'SeaLevelPressureHighInches', 
                      'SeaLevelPressureAvgInches' ,'SeaLevelPressureLowInches', 'VisibilityHighMiles',
                      'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH', 
                      'WindGustMPH', 'PrecipitationSumInches']

In [25]:
# Your code here
for col in  df.columns[4:20]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

#### Check if your code has worked by printing the data types again. You should see only two `object` columns (`Date` and `Events`) now. All other columns should be `int64` or `float64`.

In [27]:
# Your code here
df.dtypes

Date                          datetime64[ns]
TempHighF                              int64
TempAvgF                               int64
TempLowF                               int64
DewPointHighF                        float64
DewPointAvgF                         float64
DewPointLowF                         float64
HumidityHighPercent                  float64
HumidityAvgPercent                   float64
HumidityLowPercent                   float64
SeaLevelPressureHighInches           float64
SeaLevelPressureAvgInches            float64
SeaLevelPressureLowInches            float64
VisibilityHighMiles                  float64
VisibilityAvgMiles                   float64
VisibilityLowMiles                   float64
WindHighMPH                          float64
WindAvgMPH                           float64
WindGustMPH                          float64
PrecipitationSumInches               float64
Events                                object
dtype: object

# Challenge 2 - Handle the Missing Data

#### Now that we have fixed the type mismatch, let's address the missing data.

By coercing the columns to numeric, we have created `NaN` for each cell containing characters. We should choose a strategy to address these missing data.

The first step is to examine how many rows contain missing data.

We check how much missing data we have by applying the `.isnull()` function to our dataset. To find the rows with missing data in any of its cells, we apply `.any(axis=1)` to the function. `austin.isnull().any(axis=1)` will return a column containing true if the row contains at least one missing value and false otherwise. Therefore we must subset our dataframe with this column. This will give us all rows with at least one missing value. 

#### In the next cell, identify all rows containing at least one missing value. Assign the dataframes with missing values to a variable called `missing_values`.

In [33]:
# Your code here
display(df.isnull().any())
pd.set_option("display.max_rows", None, "display.max_columns", None)

Date                          False
TempHighF                     False
TempAvgF                      False
TempLowF                      False
DewPointHighF                  True
DewPointAvgF                   True
DewPointLowF                   True
HumidityHighPercent            True
HumidityAvgPercent             True
HumidityLowPercent             True
SeaLevelPressureHighInches     True
SeaLevelPressureAvgInches      True
SeaLevelPressureLowInches      True
VisibilityHighMiles            True
VisibilityAvgMiles             True
VisibilityLowMiles             True
WindHighMPH                    True
WindAvgMPH                     True
WindGustMPH                    True
PrecipitationSumInches         True
Events                        False
dtype: bool

In [41]:
missing_values = df[df.isnull().any(axis=1)==True]
missing_values

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,30.41,30.33,30.27,10.0,10.0,7.0,10.0,2.0,16.0,NaN,
6,2013-12-27,60,53,45,41.0,39.0,37.0,83.0,65.0,47.0,30.46,30.39,30.34,10.0,9.0,7.0,7.0,1.0,11.0,NaN,
7,2013-12-28,62,51,40,43.0,39.0,33.0,92.0,64.0,36.0,30.33,30.17,30.04,10.0,10.0,7.0,10.0,2.0,14.0,NaN,
42,2014-02-01,76,66,55,62.0,59.0,41.0,81.0,71.0,60.0,29.91,29.81,29.75,10.0,10.0,9.0,14.0,6.0,26.0,NaN,Rain
51,2014-02-10,60,48,35,49.0,36.0,30.0,82.0,74.0,66.0,30.23,30.15,30.02,10.0,8.0,4.0,15.0,9.0,23.0,NaN,Rain
66,2014-02-25,71,62,52,65.0,60.0,47.0,93.0,85.0,77.0,30.06,30.01,29.95,10.0,4.0,1.0,12.0,5.0,20.0,NaN,Rain
95,2014-03-26,66,60,54,55.0,47.0,30.0,78.0,57.0,36.0,30.20,30.08,29.95,10.0,10.0,6.0,22.0,10.0,33.0,NaN,Rain
102,2014-04-02,82,76,70,69.0,67.0,63.0,97.0,78.0,58.0,29.90,29.80,29.69,10.0,9.0,4.0,16.0,9.0,30.0,NaN,Rain
103,2014-04-03,82,77,71,69.0,67.0,66.0,90.0,74.0,58.0,29.81,29.74,29.66,10.0,8.0,5.0,14.0,7.0,25.0,NaN,
104,2014-04-04,74,64,54,69.0,35.0,28.0,93.0,58.0,22.0,30.14,30.03,29.82,10.0,10.0,5.0,17.0,8.0,28.0,NaN,Rain
105,2014-04-05,65,60,54,46.0,38.0,33.0,60.0,48.0,36.0,30.08,29.99,29.88,10.0,10.0,10.0,10.0,4.0,17.0,NaN,
113,2014-04-13,78,73,68,68.0,66.0,61.0,90.0,79.0,67.0,29.85,29.76,29.62,10.0,9.0,8.0,18.0,7.0,29.0,NaN,
126,2014-04-26,86,77,68,69.0,66.0,62.0,90.0,73.0,55.0,29.87,29.78,29.64,10.0,6.0,2.0,16.0,8.0,28.0,NaN,Rain
139,2014-05-09,86,76,66,71.0,68.0,58.0,87.0,69.0,50.0,29.96,29.89,29.77,10.0,5.0,1.0,20.0,5.0,39.0,NaN,"Rain , Thunderstorm"
152,2014-05-22,87,79,70,68.0,65.0,61.0,90.0,70.0,50.0,30.11,30.05,29.96,10.0,10.0,7.0,15.0,7.0,25.0,NaN,
154,2014-05-24,86,78,70,70.0,68.0,66.0,97.0,79.0,61.0,30.06,29.99,29.89,10.0,9.0,7.0,15.0,7.0,23.0,NaN,
155,2014-05-25,87,80,72,67.0,66.0,63.0,84.0,66.0,48.0,30.07,29.98,29.89,10.0,10.0,10.0,15.0,6.0,24.0,NaN,Thunderstorm
164,2014-06-03,90,83,75,72.0,70.0,68.0,82.0,67.0,52.0,30.03,29.96,29.88,10.0,10.0,10.0,10.0,6.0,17.0,NaN,
169,2014-06-08,90,83,76,72.0,70.0,64.0,87.0,67.0,46.0,29.99,29.88,29.76,10.0,10.0,5.0,16.0,7.0,27.0,NaN,Rain
174,2014-06-13,89,79,68,NaN,NaN,NaN,95.0,75.0,55.0,30.01,29.95,29.87,NaN,NaN,NaN,15.0,4.0,22.0,0.0,
175,2014-06-14,87,92,73,NaN,NaN,NaN,95.0,77.0,59.0,29.99,29.93,29.84,NaN,NaN,NaN,15.0,6.0,22.0,0.0,
176,2014-06-15,91,83,74,NaN,NaN,NaN,NaN,NaN,NaN,29.98,29.90,29.87,NaN,NaN,NaN,14.0,9.0,23.0,0.0,
177,2014-06-16,92,84,75,NaN,NaN,NaN,94.0,72.0,49.0,30.05,29.99,29.93,NaN,NaN,NaN,12.0,8.0,24.0,NaN,
182,2014-06-21,92,84,75,74.0,72.0,68.0,94.0,72.0,49.0,30.07,29.99,29.87,10.0,10.0,8.0,15.0,6.0,21.0,NaN,
183,2014-06-22,90,83,76,74.0,72.0,68.0,85.0,70.0,55.0,29.96,29.90,29.82,10.0,9.0,8.0,13.0,8.0,22.0,NaN,
188,2014-06-27,91,83,75,74.0,72.0,70.0,88.0,69.0,49.0,29.93,29.87,29.79,10.0,10.0,8.0,17.0,8.0,32.0,NaN,
189,2014-06-28,93,86,78,74.0,73.0,71.0,85.0,69.0,52.0,29.97,29.88,29.83,10.0,10.0,8.0,16.0,9.0,27.0,NaN,
248,2014-08-26,101,89,77,71.0,68.0,62.0,71.0,52.0,33.0,29.98,29.93,29.89,10.0,10.0,8.0,14.0,4.0,23.0,NaN,"Rain , Thunderstorm"
278,2014-09-25,83,73,62,66.0,62.0,57.0,90.0,74.0,58.0,30.14,30.10,30.07,10.0,10.0,8.0,13.0,3.0,20.0,NaN,
280,2014-09-27,80,74,68,69.0,66.0,64.0,93.0,78.0,62.0,30.05,30.00,29.95,10.0,10.0,8.0,9.0,2.0,14.0,NaN,Rain
292,2014-10-09,92,84,75,73.0,71.0,66.0,94.0,69.0,44.0,30.01,29.93,29.83,10.0,10.0,9.0,14.0,7.0,22.0,NaN,Rain
305,2014-10-22,83,72,61,62.0,59.0,56.0,84.0,67.0,49.0,30.12,30.06,30.03,10.0,10.0,10.0,9.0,2.0,14.0,NaN,Rain
306,2014-10-23,83,75,66,62.0,59.0,57.0,81.0,64.0,46.0,30.14,30.09,30.04,10.0,10.0,10.0,8.0,2.0,11.0,NaN,Rain
313,2014-10-30,82,73,63,61.0,59.0,54.0,93.0,72.0,51.0,30.18,30.10,30.03,10.0,10.0,9.0,8.0,2.0,10.0,NaN,Rain
317,2014-11-03,76,68,59,63.0,59.0,52.0,84.0,72.0,60.0,30.18,30.12,30.07,10.0,10.0,10.0,14.0,6.0,23.0,NaN,
356,2014-12-12,71,65,59,58.0,57.0,56.0,90.0,78.0,66.0,30.30,30.23,30.18,10.0,10.0,9.0,12.0,5.0,17.0,NaN,Rain
362,2014-12-18,60,55,49,56.0,51.0,48.0,100.0,92.0,84.0,30.14,30.10,30.06,10.0,4.0,1.0,12.0,3.0,17.0,NaN,
367,2014-12-23,59,51,43,44.0,40.0,34.0,77.0,66.0,55.0,30.02,29.81,29.63,10.0,10.0,10.0,18.0,8.0,31.0,NaN,Rain
375,2014-12-31,42,39,36,31.0,29.0,27.0,76.0,70.0,64.0,30.57,30.48,30.41,10.0,10.0,9.0,14.0,8.0,21.0,NaN,
383,2015-01-08,36,30,23,23.0,12.0,5.0,56.0,48.0,39.0,30.79,30.54,30.30,10.0,10.0,10.0,15.0,5.0,23.0,NaN,Rain
404,2015-01-29,79,66,52,55.0,49.0,34.0,100.0,68.0,35.0,30.39,30.22,30.12,10.0,10.0,6.0,16.0,4.0,25.0,NaN,
405,2015-01-30,58,53,48,39.0,36.0,33.0,63.0,52.0,40.0,30.46,30.37,30.28,10.0,10.0,10.0,14.0,6.0,23.0,NaN,Rain
411,2015-02-05,52,45,38,48.0,35.0,31.0,92.0,77.0,62.0,30.48,30.38,30.22,10.0,10.0,5.0,16.0,7.0,26.0,NaN,
421,2015-02-15,68,63,57,62.0,58.0,52.0,87.0,80.0,73.0,30.15,30.02,29.88,10.0,10.0,7.0,10.0,5.0,19.0,NaN,
441,2015-03-07,60,49,38,37.0,30.0,24.0,82.0,56.0,29.0,30.50,30.40,30.27,10.0,10.0,10.0,10.0,2.0,13.0,NaN,
466,2015-04-01,83,76,68,67.0,65.0,61.0,90.0,71.0,51.0,29.98,29.92,29.83,10.0,9.0,4.0,14.0,7.0,25.0,NaN,Rain
473,2015-04-08,79,74,69,69.0,67.0,65.0,90.0,81.0,71.0,30.00,29.92,29.83,10.0,9.0,6.0,16.0,8.0,29.0,NaN,
476,2015-04-11,70,65,59,66.0,62.0,53.0,100.0,86.0,72.0,30.12,30.04,29.96,10.0,5.0,1.0,7.0,3.0,12.0,NaN,Rain
487,2015-04-22,81,74,67,68.0,65.0,63.0,93.0,79.0,64.0,29.95,29.89,29.81,10.0,10.0,7.0,16.0,7.0,23.0,NaN,
514,2015-05-19,89,82,74,75.0,72.0,69.0,87.0,73.0,59.0,30.06,29.99,29.86,10.0,8.0,5.0,17.0,8.0,28.0,NaN,Rain
522,2015-05-27,85,76,67,75.0,70.0,64.0,94.0,82.0,69.0,30.10,30.03,29.95,10.0,9.0,6.0,12.0,5.0,18.0,NaN,"Rain , Thunderstorm"
525,2015-05-30,88,79,70,70.0,68.0,64.0,93.0,74.0,55.0,30.07,30.00,29.94,10.0,10.0,8.0,12.0,2.0,16.0,NaN,"Rain , Thunderstorm"
531,2015-06-05,90,80,69,72.0,68.0,66.0,97.0,72.0,47.0,30.08,30.00,29.95,10.0,10.0,10.0,12.0,4.0,17.0,NaN,
539,2015-06-13,95,85,75,74.0,72.0,69.0,94.0,70.0,46.0,29.90,29.84,29.78,10.0,10.0,10.0,18.0,7.0,29.0,NaN,
557,2015-07-01,91,81,71,75.0,71.0,69.0,93.0,78.0,63.0,30.07,30.01,29.97,10.0,10.0,10.0,17.0,4.0,31.0,NaN,Rain
558,2015-07-02,91,81,70,73.0,71.0,69.0,100.0,78.0,56.0,30.04,29.98,29.91,10.0,10.0,6.0,16.0,6.0,29.0,NaN,
559,2015-07-03,91,84,76,74.0,72.0,69.0,88.0,69.0,49.0,30.03,29.96,29.89,10.0,9.0,7.0,12.0,6.0,19.0,NaN,
563,2015-07-07,91,85,78,75.0,73.0,70.0,85.0,71.0,56.0,30.02,29.95,29.90,10.0,10.0,8.0,16.0,8.0,28.0,NaN,
596,2015-08-09,103,89,74,NaN,NaN,NaN,100.0,65.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,
597,2015-08-10,105,90,74,NaN,NaN,NaN,100.0,62.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,6.0,20.0,0.0,
598,2015-08-11,105,90,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,
608,2015-08-21,92,82,72,74.0,71.0,67.0,93.0,73.0,52.0,30.03,29.96,29.86,10.0,9.0,4.0,14.0,5.0,23.0,NaN,Rain
629,2015-09-11,93,84,75,75.0,73.0,68.0,94.0,72.0,49.0,29.99,29.92,29.85,10.0,8.0,4.0,12.0,3.0,20.0,NaN,
633,2015-09-15,95,84,73,72.0,70.0,68.0,87.0,67.0,46.0,30.10,30.02,29.96,10.0,10.0,7.0,16.0,5.0,26.0,NaN,
638,2015-09-20,95,82,69,70.0,63.0,57.0,90.0,60.0,30.0,30.01,29.96,29.90,NaN,NaN,NaN,9.0,3.0,15.0,0.0,
639,2015-09-21,95,84,73,71.0,64.0,53.0,87.0,57.0,26.0,30.01,29.95,29.90,NaN,NaN,NaN,12.0,4.0,16.0,0.0,
643,2015-09-25,96,84,72,67.0,64.0,60.0,79.0,58.0,36.0,30.04,30.00,29.93,10.0,10.0,10.0,12.0,2.0,19.0,NaN,"Rain , Thunderstorm"
669,2015-10-21,86,79,72,70.0,68.0,65.0,90.0,71.0,51.0,30.13,30.06,29.98,10.0,10.0,9.0,16.0,8.0,24.0,NaN,Rain
683,2015-11-04,78,70,61,68.0,64.0,59.0,100.0,82.0,64.0,30.07,30.02,29.96,10.0,9.0,5.0,13.0,5.0,20.0,NaN,Rain
700,2015-11-21,66,54,41,63.0,47.0,25.0,93.0,63.0,32.0,30.37,30.12,29.91,10.0,10.0,7.0,22.0,7.0,35.0,NaN,
704,2015-11-25,74,68,62,64.0,61.0,58.0,93.0,77.0,61.0,30.11,30.07,30.02,10.0,10.0,5.0,14.0,5.0,22.0,NaN,Rain
729,2015-12-20,67,59,51,62.0,56.0,48.0,100.0,89.0,78.0,30.35,30.12,29.99,10.0,10.0,5.0,13.0,5.0,25.0,NaN,Rain
737,2015-12-28,46,41,36,34.0,30.0,28.0,92.0,75.0,58.0,30.06,29.94,29.76,10.0,10.0,10.0,21.0,8.0,35.0,NaN,
739,2015-12-30,57,49,41,44.0,42.0,39.0,100.0,80.0,59.0,30.30,30.23,30.16,10.0,7.0,3.0,9.0,4.0,14.0,NaN,Rain
741,2016-01-01,48,46,44,36.0,33.0,28.0,66.0,60.0,53.0,30.53,30.48,30.38,NaN,NaN,NaN,15.0,8.0,24.0,NaN,Rain
742,2016-01-02,47,45,42,42.0,34.0,29.0,100.0,77.0,53.0,30.51,30.42,30.36,NaN,NaN,NaN,8.0,2.0,13.0,0.2,Rain
743,2016-01-03,62,52,41,43.0,39.0,32.0,96.0,70.0,43.0,30.36,30.30,30.22,10.0,10.0,10.0,9.0,3.0,14.0,NaN,Rain
745,2016-01-05,56,46,36,40.0,36.0,32.0,85.0,68.0,51.0,30.37,30.28,30.21,10.0,10.0,10.0,9.0,3.0,12.0,NaN,Rain
756,2016-01-16,64,54,43,43.0,37.0,33.0,76.0,61.0,46.0,30.19,29.96,29.78,10.0,10.0,10.0,20.0,5.0,29.0,NaN,Rain
766,2016-01-26,58,51,43,36.0,32.0,26.0,58.0,50.0,41.0,30.32,30.20,30.06,10.0,10.0,10.0,18.0,10.0,30.0,NaN,Rain
812,2016-03-12,74,66,57,58.0,56.0,54.0,100.0,75.0,49.0,29.97,29.90,29.81,10.0,10.0,8.0,9.0,4.0,16.0,NaN,Rain
827,2016-03-27,74,65,56,63.0,55.0,44.0,100.0,70.0,40.0,30.17,30.03,29.90,10.0,8.0,2.0,15.0,5.0,24.0,NaN,Rain
841,2016-04-10,79,72,65,66.0,62.0,59.0,87.0,75.0,62.0,30.04,29.96,29.85,10.0,10.0,10.0,21.0,8.0,32.0,NaN,
842,2016-04-11,89,80,70,71.0,68.0,66.0,93.0,74.0,55.0,29.98,29.89,29.83,10.0,10.0,6.0,15.0,5.0,26.0,NaN,
855,2016-04-24,79,71,63,67.0,63.0,58.0,93.0,79.0,64.0,29.96,29.86,29.78,10.0,10.0,10.0,13.0,6.0,20.0,NaN,
859,2016-04-28,87,75,63,73.0,66.0,56.0,93.0,71.0,48.0,29.88,29.78,29.72,10.0,8.0,2.0,15.0,7.0,25.0,NaN,
860,2016-04-29,84,80,75,74.0,73.0,72.0,94.0,82.0,70.0,29.78,29.65,29.54,10.0,7.0,3.0,14.0,7.0,23.0,NaN,Rain
862,2016-05-01,78,72,66,65.0,60.0,55.0,87.0,69.0,50.0,29.98,29.89,29.80,10.0,10.0,10.0,13.0,7.0,22.0,NaN,
863,2016-05-02,70,64,57,54.0,51.0,49.0,80.0,68.0,55.0,30.15,30.07,29.97,10.0,10.0,10.0,15.0,7.0,25.0,NaN,"Rain , Thunderstorm"
874,2016-05-13,87,79,71,70.0,67.0,64.0,79.0,69.0,58.0,30.17,30.09,29.99,10.0,10.0,10.0,8.0,4.0,13.0,NaN,
883,2016-05-22,87,80,72,75.0,72.0,69.0,93.0,82.0,70.0,30.01,29.94,29.82,10.0,10.0,6.0,14.0,5.0,22.0,NaN,
953,2016-07-31,98,88,78,75.0,73.0,67.0,91.0,66.0,40.0,30.04,29.97,29.88,NaN,NaN,NaN,13.0,6.0,21.0,0.0,
987,2016-09-03,92,83,73,74.0,72.0,69.0,94.0,73.0,52.0,29.99,29.95,29.90,10.0,9.0,5.0,10.0,3.0,17.0,NaN,
989,2016-09-05,94,84,73,77.0,74.0,72.0,94.0,77.0,59.0,30.08,30.01,29.96,10.0,10.0,9.0,14.0,5.0,19.0,NaN,"Rain , Thunderstorm"
997,2016-09-13,94,84,74,75.0,72.0,69.0,100.0,73.0,46.0,30.03,29.96,29.89,10.0,10.0,6.0,9.0,3.0,15.0,NaN,Rain
998,2016-09-14,92,84,76,76.0,71.0,69.0,82.0,66.0,49.0,30.07,30.02,29.95,10.0,10.0,9.0,14.0,3.0,18.0,NaN,Rain
1001,2016-09-17,96,85,75,75.0,72.0,70.0,90.0,67.0,46.0,30.00,29.94,29.90,10.0,10.0,10.0,7.0,1.0,NaN,0.0,
1015,2016-10-01,80,70,59,61.0,56.0,53.0,87.0,65.0,42.0,30.11,30.06,30.01,10.0,10.0,10.0,7.0,1.0,13.0,NaN,
1020,2016-10-06,92,84,76,74.0,72.0,68.0,94.0,71.0,47.0,29.97,29.91,29.83,10.0,10.0,10.0,16.0,5.0,23.0,NaN,
1021,2016-10-07,89,76,63,73.0,69.0,58.0,94.0,74.0,53.0,30.17,30.02,29.91,10.0,10.0,7.0,16.0,5.0,26.0,NaN,Rain
1028,2016-10-14,87,77,67,71.0,67.0,62.0,100.0,74.0,48.0,30.21,30.10,29.99,10.0,7.0,0.0,14.0,3.0,24.0,NaN,"Fog , Rain"
1037,2016-10-23,84,70,55,62.0,55.0,47.0,86.0,63.0,39.0,30.22,30.15,30.11,10.0,10.0,10.0,13.0,3.0,19.0,NaN,"Rain , Thunderstorm"
1038,2016-10-24,86,77,67,67.0,64.0,61.0,93.0,71.0,48.0,30.25,30.19,30.15,10.0,10.0,10.0,10.0,4.0,16.0,NaN,
1056,2016-11-11,74,65,55,60.0,57.0,54.0,100.0,79.0,57.0,30.31,30.25,30.17,10.0,8.0,2.0,8.0,2.0,12.0,NaN,Rain
1063,2016-11-18,79,66,52,68.0,55.0,31.0,90.0,62.0,34.0,30.47,30.10,29.90,10.0,10.0,10.0,17.0,7.0,29.0,NaN,Rain
1099,2016-12-24,78,72,65,68.0,66.0,64.0,100.0,85.0,69.0,30.08,30.02,29.96,10.0,9.0,5.0,17.0,7.0,28.0,NaN,
1101,2016-12-26,84,77,70,70.0,69.0,67.0,93.0,74.0,55.0,30.24,30.11,29.99,10.0,10.0,7.0,12.0,4.0,20.0,NaN,Rain
1102,2016-12-27,76,69,62,68.0,58.0,47.0,97.0,72.0,46.0,30.27,30.20,30.14,10.0,10.0,10.0,7.0,1.0,11.0,NaN,
1105,2016-12-30,55,52,49,34.0,23.0,18.0,48.0,38.0,27.0,30.51,30.31,30.09,10.0,10.0,10.0,12.0,4.0,16.0,NaN,
1106,2016-12-31,77,64,51,61.0,51.0,36.0,90.0,70.0,50.0,30.06,29.90,29.76,10.0,10.0,4.0,10.0,3.0,18.0,NaN,Rain
1107,2017-01-01,73,63,53,60.0,52.0,39.0,97.0,74.0,43.0,29.93,29.85,29.79,10.0,8.0,0.0,7.0,2.0,NaN,0.0,Fog
1125,2017-01-19,71,62,52,55.0,52.0,50.0,100.0,79.0,57.0,29.99,29.83,29.70,10.0,10.0,10.0,12.0,3.0,18.0,NaN,Rain
1134,2017-01-28,61,50,39,37.0,31.0,21.0,82.0,52.0,22.0,30.43,30.35,30.27,10.0,10.0,10.0,14.0,6.0,22.0,NaN,Rain
1140,2017-02-03,53,49,45,37.0,34.0,31.0,61.0,57.0,53.0,30.44,30.37,30.29,10.0,10.0,10.0,13.0,6.0,21.0,NaN,
1142,2017-02-05,72,62,51,64.0,59.0,51.0,100.0,89.0,78.0,30.13,30.06,29.98,10.0,6.0,0.0,12.0,3.0,19.0,NaN,Fog
1143,2017-02-06,78,73,67,67.0,65.0,63.0,93.0,76.0,58.0,30.00,29.91,29.80,10.0,9.0,3.0,12.0,5.0,22.0,NaN,Rain
1150,2017-02-13,78,71,63,64.0,55.0,42.0,84.0,63.0,42.0,30.18,30.05,29.86,10.0,10.0,10.0,18.0,9.0,28.0,NaN,
1163,2017-02-26,72,57,42,64.0,50.0,33.0,93.0,77.0,60.0,30.05,29.95,29.87,10.0,10.0,9.0,12.0,3.0,18.0,NaN,
1164,2017-02-27,82,74,66,66.0,65.0,64.0,93.0,76.0,58.0,29.98,29.92,29.85,10.0,8.0,4.0,13.0,6.0,21.0,NaN,
1171,2017-03-06,84,76,68,67.0,66.0,64.0,93.0,76.0,58.0,30.03,29.94,29.81,10.0,10.0,10.0,16.0,9.0,29.0,NaN,Rain
1172,2017-03-07,77,69,61,67.0,51.0,34.0,93.0,61.0,29.0,30.29,30.12,29.94,10.0,10.0,5.0,17.0,6.0,25.0,NaN,
1173,2017-03-08,76,68,60,64.0,50.0,33.0,78.0,56.0,34.0,30.32,30.23,30.16,10.0,10.0,10.0,12.0,4.0,17.0,NaN,
1174,2017-03-09,80,74,67,66.0,64.0,59.0,93.0,79.0,64.0,30.19,30.13,30.01,10.0,10.0,6.0,14.0,5.0,23.0,NaN,"Rain , Thunderstorm"
1175,2017-03-10,83,73,62,65.0,62.0,59.0,93.0,70.0,47.0,30.17,30.11,30.06,10.0,10.0,10.0,12.0,2.0,18.0,NaN,
1209,2017-04-13,82,75,67,66.0,64.0,58.0,100.0,77.0,54.0,30.21,30.14,30.04,10.0,9.0,5.0,14.0,6.0,23.0,NaN,Rain
1213,2017-04-17,80,72,63,67.0,65.0,57.0,90.0,80.0,69.0,30.05,30.00,29.93,10.0,10.0,6.0,16.0,5.0,26.0,NaN,"Rain , Thunderstorm"
1215,2017-04-19,85,77,68,66.0,65.0,64.0,87.0,71.0,55.0,30.08,30.02,29.95,10.0,10.0,9.0,14.0,6.0,22.0,NaN,Rain
1229,2017-05-03,95,80,64,72.0,66.0,47.0,93.0,66.0,39.0,29.97,29.80,29.67,10.0,9.0,5.0,18.0,8.0,31.0,NaN,Rain
1236,2017-05-10,83,77,71,70.0,68.0,66.0,90.0,76.0,62.0,29.98,29.91,29.86,10.0,9.0,7.0,14.0,7.0,23.0,NaN,
1244,2017-05-18,94,84,73,73.0,71.0,65.0,94.0,72.0,49.0,29.82,29.75,29.66,10.0,8.0,5.0,20.0,10.0,33.0,NaN,
1259,2017-06-02,92,83,74,72.0,71.0,66.0,93.0,70.0,47.0,29.98,29.92,29.80,10.0,10.0,10.0,12.0,5.0,16.0,NaN,
1269,2017-06-12,94,85,75,72.0,68.0,62.0,87.0,62.0,36.0,29.96,29.89,29.81,10.0,10.0,2.0,15.0,7.0,22.0,NaN,Rain
1288,2017-07-01,98,89,79,76.0,72.0,66.0,85.0,62.0,38.0,30.13,30.02,29.92,10.0,9.0,6.0,15.0,7.0,24.0,NaN,
1304,2017-07-17,98,88,77,75.0,71.0,66.0,88.0,63.0,38.0,29.94,29.90,29.84,10.0,10.0,10.0,16.0,3.0,23.0,NaN,"Rain , Thunderstorm"
1308,2017-07-21,104,91,77,74.0,68.0,61.0,85.0,56.0,27.0,30.01,29.95,29.86,10.0,10.0,10.0,14.0,5.0,24.0,NaN,
1313,2017-07-26,103,91,78,75.0,70.0,61.0,91.0,58.0,25.0,30.13,30.03,29.93,10.0,10.0,10.0,15.0,6.0,27.0,NaN,

There are multiple strategies to handle missing data. Below lists the most common ones data scientists use:

* Removing all rows or all columns containing missing data. This is the simplest strategy. It may work in some cases but not others.

* Filling all missing values with a placeholder value. 
    * For categorical data, `0`, `-1`, and `9999` are some commonly used placeholder values. 
    * For continuous data, some may opt to fill all missing data with the mean. This strategy is not optimal since it can increase the fit of the model.

* Filling the values using some algorithm. 

#### In our case, we will use a hybrid approach which is to first remove the data that contain most missing values then fill in the rest of the missing values with the *linear interpolation* algorithm.

#### Next, count the number of rows of `austin` and `missing_values`.

In [44]:
# Your code here
index = df.index
number_of_rows_austin = len(index)
index2 = missing_values.index
number_of_rows_missing = len(index2)
display(number_of_rows_austin)
display(number_of_rows_missing)

1319

136

#### Calculate the ratio of missing rows to total rows

In [47]:
# Your code here
ratio = (number_of_rows_missing / number_of_rows_austin )*100
ratio

10.310841546626232

As you can see, there is a large proportion of missing data (over 10%). Perhaps we should evaluate which columns have the most missing data and remove those columns. For the remaining columns, we will perform a linear approximation of the missing data.

We can find the number of missing rows in each column using the `.isna()` function. We then chain the `.sum` function to the `.isna()` function and find the number of missing rows per column

In [48]:
# Your code here
df.isnull().sum()

Date                            0
TempHighF                       0
TempAvgF                        0
TempLowF                        0
DewPointHighF                   7
DewPointAvgF                    7
DewPointLowF                    7
HumidityHighPercent             2
HumidityAvgPercent              2
HumidityLowPercent              2
SeaLevelPressureHighInches      3
SeaLevelPressureAvgInches       3
SeaLevelPressureLowInches       3
VisibilityHighMiles            12
VisibilityAvgMiles             12
VisibilityLowMiles             12
WindHighMPH                     2
WindAvgMPH                      2
WindGustMPH                     4
PrecipitationSumInches        124
Events                          0
dtype: int64

In [52]:
#df.drop(columns=['PrecipitationSumInches'], inplace=True)
#Dropped column with higher amnount of missng values rows

#### As you can see from the output, the majority of missing data is in one column called `PrecipitationSumInches`. What's the number of missing values in this column in ratio to its total number of rows?

In [56]:
# Your code here
import scipy.interpolate
austin_fixed = df.interpolate(method ='linear', inplace=False)
austin_fixed.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,Events
0,2013-12-21,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,29.86,29.68,29.59,10.0,7.0,2.0,20.0,4.0,31.0,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,30.41,30.13,29.87,10.0,10.0,5.0,16.0,6.0,25.0,
2,2013-12-23,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,30.56,30.49,30.41,10.0,10.0,10.0,8.0,3.0,12.0,
3,2013-12-24,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,30.56,30.45,30.30,10.0,10.0,7.0,12.0,4.0,20.0,
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,30.41,30.33,30.27,10.0,10.0,7.0,10.0,2.0,16.0,

Over 10% data missing! Therefore, we prefer to remove this column instead of filling its missing values. It doesn't make sense to *guess* its missing values because the estimation will be too 

#### Remove this column from `austin` using the `.drop()` function. Use the `inplace=True` argument.

*Hints:*

* By supplying `inplace=True` to `drop()`, the original dataframe object will be changed in place and the function will return `None`. In contrast, if you don't supply `inplace=True`, which is equivalent to supplying `inplace=False` because `False` is the default value, the original dataframe object will be kept and the function returns a copy of the transformed dataframe object. In the latter case, you'll have to assign the returned object back to your variable.

* Also, since you are dropping a column instead of a row, you'll need to supply `axis=1` to `drop()`.

[Reference for `pandas.DataFrame.drop`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html)

In [ ]:
# Your code here 


# Print `austin` to confirm the column is indeed removed

austin

#### Next we will perform linear interpolation of the missing data.

This means that we will use a linear algorithm to estimate the missing data. Linear interpolation assumes that there is a straight line between the points and the missing point will fall on that line. This is a good enough approximation for weather related data. Weather related data is typically a time series. Therefore, we do not want to drop rows from our data if possible. It is prefereable to estimate the missing values rather than remove the rows. However, if you have data from a single point in time, perhaps a better solution would be to remove the rows. 

If you would like to read more about linear interpolation, you can do so [here](https://en.wikipedia.org/wiki/Linear_interpolation).

In the following cell, use the `.interpolate()` function on the entire dataframe. This time pass the `inplace=False` argument to the function and assign the interpolated dataframe to a new variable called `austin_fixed` so that we can compare with `austin`.

In [ ]:
# Your code here

#### Check to make sure `austin_fixed` contains no missing data. Also check `austin` - it still contains missing data.

In [ ]:
# Your code here

# Challenge 3 - Processing the `Events` Column

#### Our dataframe contains one true text column - the Events column. We should evaluate this column to determine how to process it.

Use the `value_counts()` function to evaluate the contents of this column

In [ ]:
# Your code here:

Reading the values of `Events` and reflecting what those values mean in the context of data, you realize this column indicates what weather events had happened in a particular day.

#### What is the largest number of events happened in a single day? Enter your answer in the next cell.

In [ ]:
# Your answer:

#### We want to transform the string-type `Events` values to the numbers. This will allow us to apply machine learning algorithms easily.

How? We will create a new column for each type of events (i.e. *Rain*, *Snow*, *Fog*, *Thunderstorm*. In each column, we use `1` to indicate if the corresponding event happened in that day and use `0` otherwise.

Below we provide you a list of all event types. Loop the list and create a dummy column with `0` values for each event in `austin_fixed`. To create a new dummy column with `0` values, simply use `austin_fixed[event] = 0`.

In [ ]:
event_list = ['Snow', 'Fog', 'Rain', 'Thunderstorm']

# Your code here


# Print your new dataframe to check whether new columns have been created:

austin_fixed

#### Next, populate the actual values in the dummy columns of  `austin_fixed`.

You will check the *Events* column. If its string value contains `Rain`, then the *Rain* column should be `1`. The same for `Snow`, `Fog`, and `Thunderstorm`.

*Hints:*

* Use [`pandas.Series.str.contains()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.contains.html) to create the value series of each new column.

* What if the values you populated are booleans instead of numbers? You can cast the boolean values to numbers by using `.astype(int)`. For instance, `pd.Series([True, True, False]).astype(int)` will return a new series with values of `[1, 1, 0]`.

In [ ]:
# Your code here

#### Print out `austin_fixed` to check if the event columns are populated with the intended values

In [ ]:
# Your code here

#### If your code worked correctly, now we can drop the `Events` column as we don't need it any more.

In [ ]:
# Your code here

# Challenge 4 - Processing The `Date` Column

The `Date` column is another non-numeric field in our dataset. A value in that field looks like `'2014-01-06'` which consists of the year, month, and day connected with hyphens. One way to convert the date string to numerical is using a similar approach as we used for `Events`, namely splitting the column into numerical `Year`, `Month`, and `Day` columns. In this challenge we'll show you another way which is to use the Python `datetime` library's `toordinal()` function. Depending on what actual machine learning analysis you will conduct, each approach has its pros and cons. Our goal today is to practice data preparation so we'll skip the discussion here.

Here you can find the [reference](https://docs.python.org/3/library/datetime.html) and [example](https://stackoverflow.com/questions/39846918/convert-date-to-ordinal-python) for `toordinal`. The basic process is to first convert the string to a `datetime` object using `datetime.datetime.strptime`, then convert the `datetime` object to numerical using `toordinal`.

#### In the cell below, convert the `Date` column values from string to numeric values using `toordinal()`.

In [ ]:
# Your code here

#### Print `austin_fixed` to check your `Date` column.

In [ ]:
austin_fixed.head(5)

# Challenge 5 - Sampling and Holdout Sets

#### Now that we have processed the data for machine learning, we will separate the data to test and training sets.

We first train the model using only the training set. We check our metrics on the training set. We then apply the model to the test set and check our metrics on the test set as well. If the metrics are significantly more optimal on the training set, then we know we have overfit our model. We will need to revise our model to ensure it will be more applicable to data outside the test set.

#### In the next cells we will separate the data into a training set and a test set using the `train_test_split()` function in scikit-learn.

When using `scikit-learn` for machine learning, we first separate the data to predictor and response variables. This is the standard way of passing datasets into a model in `scikit-learn`. The `scikit-learn` will then find out whether the predictors and responses fit the model.

In the next cell, assign the `TempAvgF` column to `y` and the remaining columns to `X`. Your `X` should be a subset of `austin_fixed` containing the following columns: 

```['Date',
 'TempHighF',
 'TempLowF',
 'DewPointHighF',
 'DewPointAvgF',
 'DewPointLowF',
 'HumidityHighPercent',
 'HumidityAvgPercent',
 'HumidityLowPercent',
 'SeaLevelPressureHighInches',
 'SeaLevelPressureAvgInches',
 'SeaLevelPressureLowInches',
 'VisibilityHighMiles',
 'VisibilityAvgMiles',
 'VisibilityLowMiles',
 'WindHighMPH',
 'WindAvgMPH',
 'WindGustMPH',
 'Snow',
 'Fog',
 'Rain',
 'Thunderstorm']```
 
 Your `y` should be a subset of `austin_fixed` containing one column `TempAvgF`.

In [ ]:
# Your code here:

In the next cell, import `train_test_split` from `sklearn.model_selection`

In [ ]:
#Your code here:

Now that we have split the data to predictor and response variables and imported the `train_test_split()` function, split `X` and `y` into `X_train`, `X_test`, `y_train`, and `y_test`. 80% of the data should be in the training set and 20% in the test set. `train_test_split()` reference can be accessed [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).


Enter your code in the cell below:

In [ ]:
#Your code here:

#### Congratulations! Now you have finished the preparation of the dataset!